POST http://localhost:3001/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJpbmdvIiwiaWQiOiI2NTYxMGVmOGMwNzY5MmQwMDk3ODdhZjEiLCJpYXQiOjE3MDA5MjA5MTcsImV4cCI6MTcwMDkyMDk3N30.xCGyDK48pGGmeRt3hPqO7UjSraA2OVN4lJxjKBtbNHw
{
  "title": "v2.35.0-cloud.1 : Changelog",
  "author": "Hasura Team",
  "likes": 0
}